In [2]:
import numpy as np

In [9]:
vet = np.array([1, 2, 3, 6, 8, 9, 10, 11, 13, 14,15,101, 15, 13, 12, 3, 1])
vet

array([  1,   2,   3,   6,   8,   9,  10,  11,  13,  14,  15, 101,  15,
        13,  12,   3,   1])

In [4]:
type(vet)

numpy.ndarray

In [8]:
vet2 = np.array([1, 2, 3, 4, 5])
vet2.cumsum()

array([ 1,  3,  6, 10, 15])

In [11]:
print(vet[4])

8


In [13]:
vet[0] = -1
vet

array([ -1,   2,   3,   6,   8,   9,  10,  11,  13,  14,  15, 101,  15,
        13,  12,   3,   1])

In [18]:
vet = np.append(vet,202)
vet

array([ -1,   2,   3,   6,   8,   9,  10,  11,  13,  14,  15, 101,  15,
        13,  12,   3,   1, 202, 202])

In [20]:
vet = vet[:-1]
vet

array([ -1,   2,   3,   6,   8,   9,  10,  11,  13,  14,  15, 101,  15,
        13,  12,   3,   1, 202])

In [21]:
vet = np.delete(vet,-3)
vet

array([ -1,   2,   3,   6,   8,   9,  10,  11,  13,  14,  15, 101,  15,
        13,  12,   1, 202])

In [22]:
vet.shape

(17,)

In [23]:
vetor = np.array([[0, -5],[11, 300]])
vetor

array([[  0,  -5],
       [ 11, 300]])

In [24]:
vetor.shape

(2, 2)

In [25]:
vetor3x2 = np.array([[1,2],[3,4],[5,6]])
vetor3x2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
vetor3x2.shape

(3, 2)

In [28]:
vetor2x3 = np.array([[1,2,3],[4,5,6]])
vetor2x3

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
y = np.arange(2, 200, 5)
y

array([  2,   7,  12,  17,  22,  27,  32,  37,  42,  47,  52,  57,  62,
        67,  72,  77,  82,  87,  92,  97, 102, 107, 112, 117, 122, 127,
       132, 137, 142, 147, 152, 157, 162, 167, 172, 177, 182, 187, 192,
       197])

In [30]:
unicos_vet = np.unique(vet)
unicos_vet

array([ -1,   1,   2,   3,   6,   8,   9,  10,  11,  12,  13,  14,  15,
       101, 202])

In [53]:
idades = np.array([44, 45, 23, 23, 28, 19, 20, 19,17,51,29,28, 31,32])
mediaIA2 = round(idades.mean(),3)
x = mediaIA2
x

np.float64(29.214)

In [54]:
idades2 = np.array([44, 45, 23, 23, 28, 19, 20, 19,17,51,29,28, 31,32,31])
mediaIA2_1 = round(idades2.mean(),3)
y = mediaIA2_1
y

np.float64(29.333)

In [55]:
h = (x + 31)/2
h

np.float64(30.107)

In [40]:
j = np.unique(idades)
j

array([17, 19, 20, 23, 28, 29, 31, 32, 44, 45, 51])